# These are supported funding model platforms

github: [GuitarML]
patreon: GuitarML
custom: https://www.paypal.com/donate?business=H22K2S7B7ACMJ&no_recurring=0&item_name=Support+GuitarML&currency_code=USD
